name: baroo
description: "Baroo Events"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.2
  url_launcher: ^6.2.5
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
