name: events_baroo_app
description: "Baroo Events"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  url_launcher: ^6.3.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.4
  intl: ^0.19.0
  path_provider: ^2.1.5
  bloc: ^8.1.4
  meta: ^1.15.0
  collection: ^1.19.0
  flutter_multi_formatter: ^2.13.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
