name: baroo
description: "Baroo Events"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  url_launcher: ^6.2.5
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  bloc: ^8.1.4
  meta: ^1.15.0
  image_picker: ^1.1.2
  collection: ^1.18.0
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
